spring:
  config:
    activate:
      on-profile: staging
  mail:
    default-encoding: UTF-8
    smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls:
        enable: true
vitcheck:
  email:
    enabled: true
    security:
      aes-encryption-key: HLyA1ZaklP8wYHUrZXEKGQZwVXFopGvxY3hYV0SnhP4=
      aes-encryption-iv: feB62n31VV/7o1lIGn4O0Q==
  integration:
    crm:
      klaviyo:
        apiEndpoint: https://a.klaviyo.com/api
      enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

security:
  allowedOrigins: http://localhost:4000,http://localhost:4200