INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,1,'Gender','Gender',NULL,1,'Males and females often have different dietary needs e.g. during pregnancy',1,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,2,'Age Range','Age',NULL,3,'The elderly are less able to absorb Vitamin B12',1,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,3,'Fruit and veg','Portions of fruits and vegetables eaten per day',NULL,1,'Rich in antioxidant vitamins-the less you eat the more you need from other sources',2,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,5,'Smoking','Do you smoke or are you regularly exposed to second hand smoke?',NULL,2,'Smoking can increase your needs for certain vitamins such as C and D',3,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,6,'Oily fish portions','Portions of oily fish, such as salmon, mackerel, sardines, per week',NULL,3,'Rich in beneficial omega 3''s-some medications reduce levels in the body',2,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,8,'Vegetarian','Are you vegan or vegetarian?',NULL,4,'Might affect requirements for Vitamin B12',2,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,9,'Weight','Weight',NULL,4,'Being under/on target/over-weight can affect the doses of vitamins needed e.g. Vitamin D',1,4);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,10,'Height','Height',NULL,6,'Together with weight and indicator of dietary needs',1,5);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,11,'Allergies','Do you have any food sensitivities?',NULL,5,'This can influence nutrient status',2,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,12,'Exercise','How would you describe your exercise routine?',NULL,1,'High intensity exercise can increase nutrient requirements',3,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,13,'Alcohol','How would you describe your average weekly alcohol intake?',NULL,3,'This can influence B vitamin requirements',3,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,15,'Calcium-rich Food Portions','Portions of calcium rich foods such as dairy, green leafy vegetables, broccoli each day',NULL,3,'Calcium is important for bone health',2,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,16,'Sunshine Exposure','Is your exposure to summer sunshine',NULL,5,'Skin exposure to sunshine boosts vitamin D levels',3,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,17,'Weight Loss','Are you currently trying to lose more than 10lbs/5kilos in weight through following a restricted diet?',NULL,4,'Calorie restricted diets can sometimes reduce important micronutrient intake',3,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,18,'Genetic Testing','Have you ever had any genetic tests administered relating to nutrition?',NULL,7,'Certain genetic tests are able to predict if your body uses certain nutrients less well than normal',3,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,20,'Joints','Joints',NULL,1,NULL,4,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,21,'Digestive Issues','Digestive Issues',NULL,2,NULL,4,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,22,'Stress','Stress',NULL,3,NULL,4,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,23,'Energy','Energy',NULL,4,NULL,4,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,24,'Sleep','Sleep',NULL,5,NULL,4,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,25,'Hair, Skin and Nails','Hair, Skin and Nails',NULL,6,NULL,4,0);
INSERT INTO survey_question(required,id,name,label,parent_answer_id,sort_order,tooltip,section_id,question_type) VALUES (true,26,'Immunity','Immunity',NULL,7,NULL,4,0);


